import type { Layout } from './layout';
import type { MoonSpec, PlanetSpec } from './types';

const DEG_TO_RAD = Math.PI / 180;

export const SUN = { name: 'Sun', bodyRadius: 22, color: '#ffcc33' } as const;
export const MOON_STYLE = { bodyRadius: 1.5, color: '#bbbbbb' } as const;

export const ASTEROID_BELT = {
  count: 400,
  seed: 42_000,
  color: 'rgba(170, 170, 190, 0.45)',
  minRadius: 0.4,
  maxRadius: 1.6,
  getRadii(layout: Layout) {
    const mars = layout.planets.Mars;
    const jupiter = layout.planets.Jupiter;
    const gap = 10;
    return {
      inner: mars.orbitRadius + mars.bubbleRadius + gap,
      outer: jupiter.orbitRadius - jupiter.bubbleRadius - gap,
    };
  },
} as const;

export const PLANETS: PlanetSpec[] = [
  {
    name: 'Mercury',
    periodDays: 87.9691,
    epochAngleRad: 242.262456669 * DEG_TO_RAD,
    bodyRadius: 4,
    color: '#9c8e82',
  },
  {
    name: 'Venus',
    periodDays: 224.701,
    epochAngleRad: 277.021284224 * DEG_TO_RAD,
    bodyRadius: 6,
    color: '#e3bb76',
  },
  {
    name: 'Earth',
    periodDays: 365.256,
    epochAngleRad: 100.209656729 * DEG_TO_RAD,
    bodyRadius: 6,
    color: '#4d9de0',
  },
  {
    name: 'Mars',
    periodDays: 686.98,
    epochAngleRad: 283.796552295 * DEG_TO_RAD,
    bodyRadius: 5,
    color: '#c1440e',
  },
  {
    name: 'Jupiter',
    periodDays: 4332.589,
    epochAngleRad: 108.967359114 * DEG_TO_RAD,
    bodyRadius: 14,
    color: '#d8a25e',
  },
  {
    name: 'Saturn',
    periodDays: 10759.22,
    epochAngleRad: 1.552905047 * DEG_TO_RAD,
    bodyRadius: 12,
    color: '#e0c38b',
  },
  {
    name: 'Uranus',
    periodDays: 30688.5,
    epochAngleRad: 59.539656457 * DEG_TO_RAD,
    bodyRadius: 9,
    color: '#7dd3d8',
  },
  {
    name: 'Neptune',
    periodDays: 60182,
    epochAngleRad: 0.995246704 * DEG_TO_RAD,
    bodyRadius: 9,
    color: '#5b7fd4',
  },
];

export const MOONS: MoonSpec[] = [
  // Earth (1)
  { name: 'Moon', parent: 'Earth', periodDays: 27.3217, epochAngleRad: 66.351233998 * DEG_TO_RAD },
  // Mars (2)
  { name: 'Phobos', parent: 'Mars', periodDays: 0.31891 },
  { name: 'Deimos', parent: 'Mars', periodDays: 1.26244 },
  // Jupiter (20)
  { name: 'Metis', parent: 'Jupiter', periodDays: 0.2959 },
  { name: 'Adrastea', parent: 'Jupiter', periodDays: 0.2994 },
  { name: 'Amalthea', parent: 'Jupiter', periodDays: 0.499 },
  { name: 'Thebe', parent: 'Jupiter', periodDays: 0.6753 },
  { name: 'Io', parent: 'Jupiter', periodDays: 1.7693 },
  { name: 'Europa', parent: 'Jupiter', periodDays: 3.5504 },
  { name: 'Ganymede', parent: 'Jupiter', periodDays: 7.1556 },
  { name: 'Callisto', parent: 'Jupiter', periodDays: 16.69 },
  { name: 'Themisto', parent: 'Jupiter', periodDays: 129.97 },
  { name: 'Leda', parent: 'Jupiter', periodDays: 240.33 },
  { name: 'Ersa', parent: 'Jupiter', periodDays: 248.62 },
  { name: 'Himalia', parent: 'Jupiter', periodDays: 249.91 },
  { name: 'Pandia', parent: 'Jupiter', periodDays: 251.23 },
  { name: 'Lysithea', parent: 'Jupiter', periodDays: 258.5 },
  { name: 'Elara', parent: 'Jupiter', periodDays: 258.89 },
  { name: 'Dia', parent: 'Jupiter', periodDays: 277.25 },
  { name: 'Carpo', parent: 'Jupiter', periodDays: 454.4 },
  { name: 'Valetudo', parent: 'Jupiter', periodDays: 522.07 },
  { name: 'Euporie', parent: 'Jupiter', periodDays: -546.18 },
  { name: 'Eupheme', parent: 'Jupiter', periodDays: -611.32 },
  // Saturn (30)
  { name: 'Pan', parent: 'Saturn', periodDays: 0.57505 },
  { name: 'Daphnis', parent: 'Saturn', periodDays: 0.59408 },
  { name: 'Atlas', parent: 'Saturn', periodDays: 0.6046 },
  { name: 'Prometheus', parent: 'Saturn', periodDays: 0.61588 },
  { name: 'Pandora', parent: 'Saturn', periodDays: 0.63137 },
  { name: 'Epimetheus', parent: 'Saturn', periodDays: 0.69701 },
  { name: 'Janus', parent: 'Saturn', periodDays: 0.69735 },
  { name: 'Aegaeon', parent: 'Saturn', periodDays: 0.80812 },
  { name: 'Mimas', parent: 'Saturn', periodDays: 0.94242 },
  { name: 'Methone', parent: 'Saturn', periodDays: 1.00955 },
  { name: 'Anthe', parent: 'Saturn', periodDays: 1.0389 },
  { name: 'Pallene', parent: 'Saturn', periodDays: 1.15606 },
  { name: 'Enceladus', parent: 'Saturn', periodDays: 1.37022 },
  { name: 'Tethys', parent: 'Saturn', periodDays: 1.8878 },
  { name: 'Telesto', parent: 'Saturn', periodDays: 1.8878 },
  { name: 'Calypso', parent: 'Saturn', periodDays: 1.8878 },
  { name: 'Helene', parent: 'Saturn', periodDays: 2.73692 },
  { name: 'Polydeuces', parent: 'Saturn', periodDays: 2.73692 },
  { name: 'Dione', parent: 'Saturn', periodDays: 2.73692 },
  { name: 'Rhea', parent: 'Saturn', periodDays: 4.5175 },
  { name: 'Titan', parent: 'Saturn', periodDays: 15.9454 },
  { name: 'Hyperion', parent: 'Saturn', periodDays: 21.2767 },
  { name: 'Iapetus', parent: 'Saturn', periodDays: 79.331 },
  { name: 'Kiviuq', parent: 'Saturn', periodDays: 448.91 },
  { name: 'Ijiraq', parent: 'Saturn', periodDays: 451.12 },
  { name: 'Phoebe', parent: 'Saturn', periodDays: -550.3 },
  { name: 'Paaliaq', parent: 'Saturn', periodDays: 685.72 },
  { name: 'Skathi', parent: 'Saturn', periodDays: -725.73 },
  { name: 'Albiorix', parent: 'Saturn', periodDays: 779.07 },
  { name: 'Bebhionn', parent: 'Saturn', periodDays: 829.64 },
  // Uranus (29)
  { name: 'Cordelia', parent: 'Uranus', periodDays: 0.3347 },
  { name: 'Ophelia', parent: 'Uranus', periodDays: 0.3764 },
  { name: 'S/2025 U 1', parent: 'Uranus', periodDays: 0.4201 },
  { name: 'Bianca', parent: 'Uranus', periodDays: 0.4347 },
  { name: 'Cressida', parent: 'Uranus', periodDays: 0.4639 },
  { name: 'Desdemona', parent: 'Uranus', periodDays: 0.4736 },
  { name: 'Juliet', parent: 'Uranus', periodDays: 0.4931 },
  { name: 'Portia', parent: 'Uranus', periodDays: 0.5132 },
  { name: 'Rosalind', parent: 'Uranus', periodDays: 0.5583 },
  { name: 'Cupid', parent: 'Uranus', periodDays: 0.6125 },
  { name: 'Belinda', parent: 'Uranus', periodDays: 0.6236 },
  { name: 'Perdita', parent: 'Uranus', periodDays: 0.6382 },
  { name: 'Puck', parent: 'Uranus', periodDays: 0.7618 },
  { name: 'Mab', parent: 'Uranus', periodDays: 0.9229 },
  { name: 'Miranda', parent: 'Uranus', periodDays: 1.4135 },
  { name: 'Ariel', parent: 'Uranus', periodDays: 2.5204 },
  { name: 'Umbriel', parent: 'Uranus', periodDays: 4.1442 },
  { name: 'Titania', parent: 'Uranus', periodDays: 8.7059 },
  { name: 'Oberon', parent: 'Uranus', periodDays: 13.463 },
  { name: 'Francisco', parent: 'Uranus', periodDays: -267 },
  { name: 'Caliban', parent: 'Uranus', periodDays: -580 },
  { name: 'Stephano', parent: 'Uranus', periodDays: -677 },
  { name: 'S/2023 U 1', parent: 'Uranus', periodDays: -681 },
  { name: 'Trinculo', parent: 'Uranus', periodDays: -749 },
  { name: 'Sycorax', parent: 'Uranus', periodDays: -1286 },
  { name: 'Margaret', parent: 'Uranus', periodDays: 1655 },
  { name: 'Prospero', parent: 'Uranus', periodDays: -1974 },
  { name: 'Setebos', parent: 'Uranus', periodDays: -2215 },
  { name: 'Ferdinand', parent: 'Uranus', periodDays: -2788 },
  // Neptune (16)
  { name: 'Naiad', parent: 'Neptune', periodDays: 0.2944 },
  { name: 'Thalassa', parent: 'Neptune', periodDays: 0.3115 },
  { name: 'Despina', parent: 'Neptune', periodDays: 0.3347 },
  { name: 'Galatea', parent: 'Neptune', periodDays: 0.4287 },
  { name: 'Larissa', parent: 'Neptune', periodDays: 0.5547 },
  { name: 'Hippocamp', parent: 'Neptune', periodDays: 0.9504 },
  { name: 'Proteus', parent: 'Neptune', periodDays: 1.1223 },
  { name: 'Triton', parent: 'Neptune', periodDays: -5.8769 },
  { name: 'Nereid', parent: 'Neptune', periodDays: 360.14 },
  { name: 'Halimede', parent: 'Neptune', periodDays: -1879.08 },
  { name: 'Sao', parent: 'Neptune', periodDays: 2912.72 },
  { name: 'S/2002 N 5', parent: 'Neptune', periodDays: 3156.55 },
  { name: 'Laomedeia', parent: 'Neptune', periodDays: 3171.33 },
  { name: 'Psamathe', parent: 'Neptune', periodDays: -9149.51 },
  { name: 'Neso', parent: 'Neptune', periodDays: -9794.71 },
  { name: 'S/2021 N 1', parent: 'Neptune', periodDays: -10036.65 },
];
